import {
  Atom,
  Braces,
  BrainCircuit,
  Rocket,
  ShieldCheck,
  TrendingUp,
  Palette,
  Cloud,
  Layers,
  FlaskConical,
  Megaphone,
  GitBranch,
  Terminal,
  Zap,
  Link2,
  BarChart2,
  BookOpen,
  FileCode,
  Network,
  Briefcase,
  Gamepad2,
  Heart,
  Smartphone,
  Database,
  Workflow,
  Hammer,
  Users,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

const TOPIC_ICONS: Record<string, LucideIcon> = {
  "react":          Atom,
  "javascript":     Braces,
  "ai-ml":          BrainCircuit,
  "startups":       Rocket,
  "cybersecurity":  ShieldCheck,
  "finance":        TrendingUp,
  "design":         Palette,
  "devops":         Cloud,
  "product":        Layers,
  "science":        FlaskConical,
  "marketing":      Megaphone,
  "open-source":    GitBranch,
  "python":         Terminal,
  "productivity":   Zap,
  "blockchain":     Link2,
  "data-science":   BarChart2,
  "typescript":     FileCode,
  "system-design":  Network,
  "career":         Briefcase,
  "gaming":         Gamepad2,
  "health":         Heart,
  "mobile":         Smartphone,
  "database":       Database,
  "golang":         Workflow,
  "rust":           Hammer,
  "leadership":     Users,
}

export function getTopicIcon(slug: string): LucideIcon {
  return TOPIC_ICONS[slug] ?? BookOpen
}
